developmentseed/work.vote

app/assets/styles/_base.scss

Suggestion text to black

---

app/assets/scripts/components/footer.js
app/assets/scripts/components/frontpage.js
app/assets/scripts/components/header.js
app/assets/scripts/components/result.js
app/assets/styles/_base.scss

Fix images

---

app/assets/scripts/views/contact.js
app/assets/styles/_base.scss

@DylanMoriarty 
Check this out for me when you get the chance?
Thanks!
Lauren

Contact form

---

app/assets/scripts/components/footer.js
app/assets/styles/_base.scss

Redid footer. Should be good to go now! @scisco

Footer changes

---

app/scripts/views/contact.js

Fix contact e-mail

---

app/index.html

Creating a meta tag for google indexing

Meta tag for indexing

---

app/scripts/config.js
app/scripts/config/staging.js

This adds the config file needed for staging api

add support for staging api

---

app/scripts/views/jurisdiction.js
app/scripts/views/state.js

As requested by @nayelipelayo.
Screenshots:

Add messaging to contact local election official when info not available

---

app/scripts/views/jurisdiction.js

Remove superfluous fields.

---

app/scripts/components/footer.js
app/scripts/views/jurisdiction.js
app/scripts/views/states.js
app/styles/_base.scss

- see #134 
- update api in pr : https://github.com/developmentseed/api.work.vote/pull/111
-  `city_model` is the field for the city relation

disambiguation notice

---

app/scripts/views/jurisdiction.js
app/scripts/views/states.js

Closes #137 
* Remove last updated
* Remove email registration requirement

Remove fields from jurisdiction page

---

app/scripts/views/jurisdiction.js

* Change callout text
* Change linking text
* Change some text in the jurisdiction page

Text changes

---

app/scripts/views/jurisdiction.js

Needs trusted-notes update to backend first.

Add trusted_notes to front-end

---

app/index.html

I think the image is not optimal, but better than the current one at least.

Fix typos and update logo for social media meta tags.

---

app/scripts/actions.js
app/scripts/components/search.js
app/scripts/views/frontpage.js
app/styles/_base.scss

This adds a filter to the front page jurisdiction search which filters the returned search values by the state. This requires https://github.com/developmentseed/api.work.vote/pull/119 to be deployed

State selector on frontpage

---

app/styles/_base.scss

style fixes

---

app/scripts/config.js

Fix typos in survey ageOptions.

Bugfix ageOptions

---

.circleci/config.yml
app/scripts/views/frontpage.js
app/styles/_base.scss

Request from Ryan:
_Allowing state dropdown list to respond to typing (i.e. show texas when someone types T)_

Adds better frontpage state selection

---

app/scripts/views/jurisdiction.js

Clarifying language regarding voter registration and minimum age requirements

---

app/scripts/views/jurisdiction.js

Adds update for Language for Student pollworkers

updates based on Ryan's email
